on: push

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
          key: ${{ runner.os }}-cabal-cache

      - name: Build
        run: cabal v2-update && cabal v2-install validator

      - name: Install toml-test
        run: |
          FILE=toml-test-v1.1.0-linux-amd64
          curl -sSLO "https://github.com/BurntSushi/toml-test/releases/download/v1.1.0/${FILE}.gz"
          gunzip "${FILE}.gz"
          chmod +x "${FILE}"
          mv "${FILE}" /usr/local/bin/toml-test

      # TODO: remove all "-skip" flags
      - name: Validate
        run: |
          PATH=~/.cabal/bin:$PATH
          toml-test toml-parser-validator \
            -skip valid/inline-table/key-dotted \
            -skip valid/key/dotted \
            -skip valid/key/numeric-dotted \
            -skip valid/string/multiline-quotes \
            -skip valid/string/multiline \
            -skip valid/table/array-nest \
            -skip valid/table/array-table-array \
            -skip valid/table/names \
            -skip invalid/control/bare-cr \
            -skip invalid/control/comment-cr \
            -skip invalid/control/comment-del \
            -skip invalid/control/comment-lf \
            -skip invalid/control/comment-null \
            -skip invalid/control/comment-us \
            -skip invalid/control/multi-del \
            -skip invalid/control/multi-lf \
            -skip invalid/control/multi-null \
            -skip invalid/control/multi-us \
            -skip invalid/control/rawmulti-del \
            -skip invalid/control/rawmulti-lf \
            -skip invalid/control/rawmulti-null \
            -skip invalid/control/rawmulti-us \
            -skip invalid/control/rawstring-del \
            -skip invalid/control/rawstring-lf \
            -skip invalid/control/rawstring-null \
            -skip invalid/control/rawstring-us \
            -skip invalid/control/string-bs \
            -skip invalid/control/string-del \
            -skip invalid/control/string-lf \
            -skip invalid/control/string-null \
            -skip invalid/control/string-us \
            -skip invalid/inline-table/add \
            -skip invalid/inline-table/linebreak-1 \
            -skip invalid/inline-table/linebreak-2 \
            -skip invalid/inline-table/linebreak-3 \
            -skip invalid/inline-table/linebreak-4 \
            -skip invalid/key/after-array \
            -skip invalid/key/after-table \
            -skip invalid/key/after-value \
            -skip invalid/key/multiline \
            -skip invalid/key/newline \
            -skip invalid/key/no-eol \
            -skip invalid/string/bad-codepoint \
            -skip invalid/table/duplicate-table-array \
            -skip invalid/table/duplicate \
            -skip invalid/table/llbrace \
            -skip invalid/table/rrbrace
